GET http://127.0.0.1:1880/usuario

###

POST http://127.0.0.1:1880/usuario
content-type: application/json

{
    "nome": "Gazetta"
}

###


GET https://agenda-backend-java.herokuapp.com/usuario

###

POST https://agenda-backend-java.herokuapp.com/usuario
content-type: application/json

{
    "nome": "Gazetta"
}